config/routes.rb
Rails.application.routes.draw do
  resources :packages
  get 'couriers/index'
  get 'couriers/new', to: 'couriers#new', as: "new"
  get 'couriers/show/:id', to: 'couriers#show', as: "show"
  get 'couriers/edit/:id', to: 'couriers#edit', as: "edit"
  post 'couriers/edit/:id', to: 'couriers#update', as: "update"
  post 'couriers/new', to: 'couriers#create'
  post 'couriers/update', to: 'couriers#update'

  
  get 'packages/new/:id', to: 'packages#new', as: "delivery"
  get 'packages/new/:i', to: 'packages#show', as: "delivery"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
    has_many :packages   
end

app/models/package.rb
class Package < ApplicationRecord
    belongs_to :courier, :optional => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  def index
    @couriers = Courier.all
  end
 
  def new
    @courier = Courier.new
    respond_to do |format|
      format.html{render :new, locals: {courier: @courier}}
    end  
  end
 

  def show
    @courier = Courier.find(params[:id]) 
    @deliveryInfo = Package.where(courier_id:params[:id]).order(created_at: :desc)
    respond_to do |format|
      format.html{render :show, locals: {courier: @courier}} 
    end 
    
  end


  def edit
    @courier = Courier.find(params[:id]) 
    respond_to do |format|
      format.html{render :edit, locals: {courier: @courier}}
    end  
  end

  def update
    @courier = Courier.find(params[:id])
    @courier.update(courier_params)

    redirect_to show_path(@courier)
  end

  def create
    courier = Courier.create(courier_params)
    redirect_to couriers_index_path 
  end  

  private

  def courier_params
    params.require(:courier).permit(:name, :email);
  end  
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: %i[ show edit update destroy ]

  # GET /packages or /packages.json
  def index
    @packages = Package.all
  end

  # GET /packages/1 or /packages/1.json
  def show
   
  end

  # GET /packages/new
  def new
    @package = Package.new
  end

  # GET /packages/1/edit
  def edit
  end

  # POST /packages or /packages.json
  def create
    @package = Package.new(package_params) 
      
    respond_to do |format|
      if @package.save
        format.html { redirect_to @package, notice: "Package was successfully created." }
        format.json { render :show, status: :created, location: @package }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packages/1 or /packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to @package, notice: "Package was successfully updated." }
        format.json { render :show, status: :ok, location: @package }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packages/1 or /packages/1.json
  def destroy
    @package.destroy
    respond_to do |format|
      format.html { redirect_to packages_url, notice: "Package was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package
      @package = Package.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def package_params
      params.require(:package).permit(:courier_id, :tracking_number, :delivery_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/add.html.erb
<h1>hello its add page</h1>

app/views/couriers/edit.html.erb
<%= __FILE__ %>
<h1>Update couriers profile</h1>
<%= form_with model: courier, url:edit_path, method: :post, local: true do |form| %>
    <%=form.label "name"%><br>
    <%=form.text_field :name, placeholder: "name" %><br>
    <%=form.label "email"%><br>
    <%=form.text_field :email, placeholder: "email" %><br>
    <%=form.submit %>   
   <% end %> 

app/views/couriers/index.html.erb
<%= __FILE__ %>
<h1>List of couriers:</h1>
<table>
<tbody>
<% @couriers.each do |courier| %>
  <tr>
    <td><%= courier.name %></td>
    <td><%= courier.email %></td>  
    <td><%= link_to "show", "show/"+courier.id.to_s %></td>
  </tr>
<% end %>
</tbody>
</table>
<div>
  <button>
    <%= link_to 'add courier', "new" %>
  </button>
</div>

app/views/couriers/new.html.erb
<h1>Please fill the blank information about couriers</h1>
<%= form_with model: courier, url: new_path, method: :post, local: true do |form| %>
 <%=form.label "name"%><br>
 <%=form.text_field :name, placeholder: "name" %><br>
 <%=form.label "email"%><br>
 <%=form.text_field :email, placeholder: "email" %><br>
 <%=form.submit %>   
<% end %>    

app/views/couriers/show.html.erb
<%= __FILE__ %>
<h2>Courier information</h2>
<table>
<tbody>
  <tr>
    <td> courier name  </td>
    <td> courier email </td>  
  </tr>
  <tr>
    <td><%= courier.name %></td>
    <td><%= courier.email %></td>  
  </tr>
</tbody>
</table>




<div>
  <button>
    <%= link_to '<<back', couriers_index_path  %>
  </button>
  <button>
    <%= link_to 'edit>>', edit_path %>
  </button>
</div>


<table>
  <thead>
    <tr>
      <th>Tracking number</th>
      <th>Delivery status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveryInfo.each do |package| %>
      <tr>
        <td><%= package.tracking_number %></td>
        <td><%= package.delivery_status %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<button>
  <%= link_to 'add delivery', delivery_path %>
</button>

app/views/couriers/update.html.erb
<%= __FILE__ %>
<h1>Update couriers profile</h1>
<%= form_with model: courier, url: update_path, method: :post, local: true do |form| %>
    <%=form.label "name"%><br>
    <%=form.text_field :name, placeholder: "name" %><br>
    <%=form.label "email"%><br>
    <%=form.text_field :email, placeholder: "email" %><br>
    <%=form.submit %>   
   <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>